repository_type: pipeline

nf_core_version: 3.4.1

lint:
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-hpcdockbench_logo_light.png
    - docs/images/nf-core-hpcdockbench_logo_light.png
    - docs/images/nf-core-hpcdockbench_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-hpcdockbench_logo_light.png
    - docs/images/nf-core-hpcdockbench_logo_light.png
    - docs/images/nf-core-hpcdockbench_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: ablab
  name: hpcdockbench
  description: A bioinformatics pipeline to perform docking benchmark on Astex and
    PoseBusters data sets.
  author: Hovakim Grabski, Siranuysh Grabska, Ruben Abagyan
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features: []
  is_nfcore: false
